### ISSUE TITLE
is_device_ptr not recongised

### ISSUE THREAD

**Issue by reguly** [clang-ykt/clang#1] opened 2016-10-21 17:54 UTC
I am getting the following error when using is_device_ptr:
clang++  -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda is_dev_ptr.cpp -c
is_dev_ptr.cpp:5:50: error: unexpected OpenMP clause 'is_device_ptr' in directive '#pragma omp target teams distribute parallel
      for'
#pragma omp target teams distribute parallel for is_device_ptr(v)
                                                 ^
1 error generated.

is_device_ptr.cpp:
```
#include <stdio.h>

int dev_ptr_bug(int *v, int len){

#pragma omp target teams distribute parallel for is_device_ptr(v)
  for(int i=0;i<len;++i){
    v[i]=-i;
  }

}
```

**Comment by grypp** [comment] 2016-10-24 10:54
Hi,
Actually when I add the following lines into OpenMPKinds.def, the code works with me. Is that enough for patch ? But I guess, there are something more to do that I am missing :) 

OPENMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR_CLAUSE(is_device_ptr)
OPENMP_TARGET_PARALLEL_FOR_CLAUSE(is_device_ptr)
OPENMP_TARGET_TEAMS_CLAUSE(is_device_ptr)

**Comment by arpith-jacob** [comment] 2016-10-24 14:07
Hi Guray, Yes I think that's all that is required.  You'll also have to add regression tests.  Here is the commit that added is_device_ptr.  
https://github.com/clang-ykt/clang/commit/cfd99ab106a35a86c403fd937203ee7a899ccaed
Could you also add use_device_ptr?

**Comment by grypp** [comment] 2016-10-24 16:19
Hi Arpith, 
I've just submitted patch for it. It works with me but please take a look

In terms of "use_device_ptr" - It seems it's implemented only for target data and afaik it is fine. Because spec says: 
"The target construct provides a superset of the functionality provided by the target data directive, except for the use_device_ptr clause."" **OpenMP 4.5 spec page 105**

**Comment by reguly** [comment] 2016-10-25 14:57
Thank you - this seems to be working throughout my code now, giving a 2x performance improvement over the map(to:cuda_ptr) hack, in part thanks to enabling texture loads. Should I close the issue?

**Comment by sfantao** [comment] 2016-10-25 15:01
Yes, let's close the issue.

Thanks!
Samuel

**Closed by sfantao** 2016-10-25 15:01 UTC

**Comment by reguly** [comment] 2016-10-25 18:12
I am more of a user of the compiler than a developer, Carlo recommended that I submit this as an issue.
